### PR TITLE
Support for wildcard inside import statement

### PR DESCRIPTION
**Pull request by akolmakov**
I've slightly extended regex to support \* inside import statements. For example, com.foo.*.bar.

### CODE REVIEW

**Comment by aarondav** [comment]
Thanks for the patch! Out of curiosity, what is the exact use-case you have in mind that requires a middle-wildcard?

**Comment by akolmakov** [comment]
After I added company's import like com.company.\* I also tried to add com.company.*.global (to do not write full path because it is quite long) after that import because we have a rule to place implicit val imports after other company's ones. It did not work. I thought it would be useful for others as well.

**Comment by aarondav** [comment]
Cool, thanks! It would be cool if we had a way to order implicits specially in general, but doing so is likely nontrivial. Merging this in, will release a new version of the plugin this weekend to include it.

**Comment by akolmakov** [comment]
Agree. It would be useful. I could take a look at this. Another thing is to
have the project as sbt/maven one. Because creating it from scratch is not
so trivial.

**Comment by aarondav** [comment]
Yeah, definitely a good point...

**Pull request merged**
